version: "3.7" # https://docs.docker.com/compose/compose-file/

services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'

  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '${OPENCART_PORT}:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
  tests:
    container_name: otus_ui_test
    build:
      context: .
      dockerfile: Dockerfile
    command: --mode=remote --hub=${LOCAL_IP} --hub_port=4444 --base_url=http://${LOCAL_IP}:${OPENCART_PORT}
    volumes:
      - type: volume
        source: test_allure
        target: /app/allure-results
        read_only: false
    depends_on:
      - opencart
      - mariadb
    networks:
      defaults:

networks:
  defaults:
    external:
      name: selenoid

volumes:
  test_allure:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './allure-results'
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
